# Avoid users needing to install this globally on their computers:
# https://aka.ms/vs/17/release/vc_redist.x64.exe
# to avoid DLL errors with C/C++ runtime libraries.

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
